name: radar-nowcasting

channels:
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - matplotlib
  - opencv
  - pillow
  - pyproj
  - netcdf4
  - h5py
  - pip:
      - pysteps==1.21.5